### ISSUE TITLE
Add Bluetooth LE Support

### ISSUE THREAD

**Issue by mikemey01** [mikemey01/ChariotGaugeAndroid#9]

**Comment by mikemey01** [comment]
Complete in version 1.7

**Comment by highvelcty** [comment]
Awesome work! I will give it a try as soon as I can. Thanks for testing the
firmware for me.

On Sun, May 17, 2015 at 8:20 PM, Mike Meyer notifications@github.com
wrote:

> Closed #9 https://github.com/mikemey01/ChariotGaugeAndroid/issues/9.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikemey01/ChariotGaugeAndroid/issues/9#event-306964383
> .

## 

ericallenmeyer@gmail.com
